name=input("Enter your name")
branch=input("Enter your branch")
gender=input("Enter your gender")
college=input("Enter your college name")
Age=int(input("Enter your age"))
print("Name is:",name)
print("\nYour branch is:",branch)
print("\nGender:",gender)
print("\nCollege name:",college)
print("\nYour age:",Age)
